package com.app.classbook.util

interface Constant {
    companion object {

        const val BASE_URL = "https://www.classbookonline.com/api/v1/"

        //        const val BASE_URL = "https://classbookapplication.wn.r.appspot.com/api/v1/"
        const val ABOUT_US = "https://www.classbookonline.com/Common/AboutUsAPI"
        const val PRIVACY_POLICY = "https://www.classbookonline.com/Common/PrivacyPolicyAPI"
        const val COOKIES = "https://www.classbookonline.com/Common/CookiesAPI"
        const val HOWITWORKSAPI = "https://www.classbookonline.com/Common/HowItWorksAPI"
        const val DISCLAMIER = "https://www.classbookonline.com/Common/DisclamierAPI"
        const val EULAPOLICIESAPI = "https://www.classbookonline.com/Common/EULAPoliciesAPI"
        const val RETURNANDREFUNDPOLICY =
            "https://www.classbookonline.com/Common/ReturnAndRefundPolicyAPI"
        const val TERMSOFCONDITIONSAPI =
            "https://www.classbookonline.com/Common/TermsOfConditionsAPI"
        const val CONTACTUSAPI = "https://www.classbookonline.com/Common/ContactUsAPI"
        const val LOGIN = "Common/Login"
        const val ClASS_REGISTER = "Classes/Register"
        const val SCHOOL_REGISTER = "School/Register"
        const val STUDENT_REGISTER = "Student/Register"
        const val TEACHER_REGISTER = "Teacher/Register"
        const val EXPERT_REGISTER = "CareerExpert/Register"
        const val FORGOT_PWD = "Common/ForgotPassword"
        const val CHANGE_PWD = "Common/ChangePassword"
        const val STATES = "Common/GetStates"
        const val CITY = "Common/GetCitiesByStateId/{id}"
        const val PINCODE = "Common/GetPincodeByCityId/{id}"
        const val BOARD = "Common/GetBoard"
        const val MEDIUM = "Common/GetMedium"
        const val STANDARD = "Common/GetStandard"
        const val SUBJECT = "Common/GetSubject"
        const val SUBJECT_SPECIALITIES = "Common/GetSubjectSpeciality"
        const val COURSES = "CourseAPI/GetCourseCategory"
        const val All_CLASSES = "Classes/GetAllClasses"
        const val CLASS_DETAIL = "Classes/GetClassById/{id}"
        const val All_TEACHER = "Teacher/GetAllTeacher"
        const val TEACHER_DETAIL = "Teacher/GetTeacherById/{id}"
        const val All_COURSES = "CourseAPI/GetCourses"
        const val COURSES_DETAIL = "CourseAPI/CourseDetail/{id}"
        const val COURSES_SUBTOPICS = "CourseAPI/CourseTopics/{topicId}/{courseId}"
        const val COURSES_SUBTOPICSVIDEO =
            "CourseAPI/CourseSubtopicVideos/{topicId}/{courseId}/{subtopicId}"
        const val All_EXPERTS = "CareerExpert/GetAllCareerExpert"
        const val EXPERT_CAREER_DETAIL = "CareerExpert/GetCareerExpertById/{id}"
        const val ADD_TO_CART = "ShoppingCart/AddToCart"
        const val ADVERTISMENT_BANNER = "Common/GetAdvertisementBanner"
        const val ADD_TO_FAV = "Common/AddToFavourite"
        const val GETBOARD = "Common/GetBoard"
        const val CART_LIST = "ShoppingCart/GetCartDetail"
        const val SUBJECTLIST = "Common/Subject/{smbId}"
        const val TOPIC_DATA = "Common/SubjectTopics/smbid/subjectId"
        const val SUB_TOPIC_DATA = "Common/TopicSubtopics/smbid/subjectId/topicId"
        const val SUB_VIDEO_DATA = "Common/SubtopicVideos/smbid/subjectId/topicId/subtopicId"
        const val GET_SUBSCRIPTION_DETAIL = "ShoppingCart/GetSubscriptionDetail"
        const val REMOVE_FROM_CART = "ShoppingCart/RemoveFromCart/{cartItemId}"
        const val GET_FAVOURITE = "Common/GetFavourite"
        const val GETSTUDENTBYID = "Student/GetStudentById"
        const val EDITSTUDENT = "Student/EditStudent"
        const val GETSTANDARDMEDIUMBOARDMAPPING = "Classes/GetStandardMediumBoardMapping/{id}"
        const val LEARNANDEARNREGISTRATIONPROCESSLIST = "LearnAndEarn/RegistrationProcessList"
        const val LEARNANDEARNREGISTRATIONPROCESSDETAIL =
            "LearnAndEarn/RegistrationProcessDetail/{id}"
        const val HOWTOEARNLIST = "LearnAndEarn/HowToEarnList"
        const val HOWTOEARNDETAIL = "LearnAndEarn/HowToEarnDetail/{id}"
        const val TRAININGVIDEOLIST = "TrainingVideo/List"
        const val TRAININGVIDEODETAIL = "TrainingVideo/TrainingVideoDetail/{id}"
        const val PERCENTAGEEARNINGS = "LearnAndEarn/PercentageEarnings"

        const val SECRET_KEY = "ClassBook-y18PJltrUUfTYFfgvUpNkIs7YBLfHRA1"
        const val USER_TYPE_STUDENT = "6"
        const val USER_TYPE_TEACHER = "7"
        const val USER_TYPE_CLASS = "8"
        const val USER_TYPE_CAREER_EXPERT = "9"
        const val USER_TYPE_COURSES = "10"
    }
}